import Head from "next/head";
import { ScrapeContext } from "../contexts/ScrapeContext"
import { useContext, useEffect, useState } from "react";
import { AuthContext } from "@/contexts/AuthContex";
import { LinearProgress, Skeleton } from "@mui/material";
import { ThemeContext } from "@/contexts/ThemeContext";
import FavoriteBorderIcon from '@mui/icons-material/FavoriteBorder';
import FavoriteIcon from '@mui/icons-material/Favorite';
import { FavoritesContext } from "@/contexts/FavoritesContext";

const Home = () => {
  const { datas, getRandomData, productsByCategory } = useContext(ScrapeContext)
  const { user } = useContext(AuthContext)
  const { systemTheme, setSystemTheme } = useContext(ThemeContext)
  const { addFavorite } = useContext(FavoritesContext)
  const [showMessage, setShowMessage] = useState(true);
  const [isFavorited, setIsFavorited] = useState(false);
  
  useEffect(()=> {
    console.log("i user",user)
   
    getRandomData()
    // 3 saniye sonra durumu değiştir
    const timer = setTimeout(() => {
      setShowMessage(true)
    }, 1000)

    // Temizlik fonksiyonu
    return () => clearTimeout(timer);
  }, [user])

  const isFavorite = (productId) => {
    console.log("isFavorite")
    addFavorite(user.uid, productId)
    setIsFavorited(!isFavorited)
  };

  const isNotFavorite = (productId) => {
    addFavorite(user.uid, productId)
    setIsFavorited(!isFavorited)
  };

  return (
    <div style={{ color: systemTheme ? "red" : "black" }}>
      <Head>
        <title>PriceWise</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {showMessage ? (
          user ? user.emailVerified ? 
          <div className="container-fluid home">
            <div className="cardRow">
                  {
                    datas ? datas.map((item) => 
                      <div key={item.id} className="col-md-3 mt-3 p-0">
                        <div className="homeCard">
                          <div className="favoriteButton" style={{ cursor: 'pointer' }}>
                              <FavoriteBorderIcon onClick={() => isFavorite(item.id)} sx={{ color: 'rgb(53, 212, 153)' }} />
                          </div>
                          
                          <img src={item.resim_url} className="productImage" alt={item.urunAdi} />
                            <h6 className="prdctName pt-4">{item.urunAdi.length > 30 ? item.urunAdi.substring(0, 30) + "..." : item.urunAdi}</h6>
                            <span style={{ color: systemTheme ? "red" : "black" }} className={`prdctPrice ${systemTheme && ``}`}>{item.fiyat} TL</span> <span>{item.sellers?.[0]?.saticiAdi}</span>
                        </div>
                      </div>
                    ) : null
                  }
            </div>
          </div> :
          null : 
          <div className="container-fluid home">
            <div className="cardRow">
                  {
                    datas ? datas.map((item) => 
                      <div key={item.id} className="col-md-3 mt-3 p-0">
                        <div className="homeCard">
                            {isFavorited ? (
                              <FavoriteIcon onClick={() => isNotFavorite(item.id)} sx={{ color: 'rgb(53, 212, 153)' }} />
                            ) : (
                              <FavoriteBorderIcon onClick={() => isFavorite(item.id)} sx={{ color: 'rgb(53, 212, 153)' }} />
                            )}
                          <img src={item.resim_url} className="productImage" alt={item.urunAdi} />
                            <h6 className="prdctName pt-4">{item.urunAdi.length > 30 ? item.urunAdi.substring(0, 30) + "..." : item.urunAdi}</h6>
                            <span style={{ color: systemTheme ? "red" : "black" }} className="prdctPrice">{item.fiyat} TL</span> <span>{item.sellers?.[0]?.saticiAdi}</span>
                        </div>
                      </div>
                    ) : null
                  }
            </div>
          </div>
      ) : (
        <div className="skeleton" style={{ backgroundColor: systemTheme ? "black" : "rgb(246, 246, 246)" }}>
          <LinearProgress />
        </div>
      )}
    </div>
  );
}

export default Home
